### ISSUE TITLE
Is it free software?

### ISSUE THREAD

**Issue by egils-consulting** [Samillion/mpv-ytdlautoformat#1]
Could you add a licence file?

**Comment by Samillion** [comment]
Yeah, it's just a script. I don't really mind if anyone wants to fork it, remake it or alter it. Greater good and all that jazz. I'll add a license to it now, but like I said, feel free to do with the code as you please.

**Comment by egils-consulting** [comment]
I tried it today and like it a lot. Thanks a lot for writing and sharing it 😃

**Comment by Samillion** [comment]
You're very welcome, I'm glad it was of use to you.
