### ISSUE TITLE
yt-dlp compatibility

### ISSUE THREAD

**Issue by newact** [Samillion/mpv-ytdlautoformat#4]
Is this script compatible with youtube-dl fork "yt-dlp"? The original youtube-dl hasn't been updated since 06.06.21 and there are already performance issues with it (like download speed capping at 50Kb/s). But some people forked it to yt-dlp, which has significantly better download speeds. Will this work with new fork? Because if the youtube-dl is not usable, this script is less usable as a consequence.

**Comment by Samillion** [comment]
Indeed it is, I've also switched to `yt-dlp` and it's working just fine. No need to change anything within the script itself, as that side of things is handled by MPV itself.

**Comment by newact** [comment]
@Samillion nice! Couldn't figure out whether it's a VM/driver compatibility issue(learning some distros) or something else. Turned out to be youtube-dl problem. Should I close the issue?

**Comment by Samillion** [comment]
I went through a very similar experience😄then I saw how mpv officially switched to yt-dlp in their [notes](https://github.com/mpv-player/mpv/releases/tag/v0.34.0) recently as the preferred choice..

Glad all is well, I'll close the issue. If you have any other questions, never hesitate to open another issue.
