### ISSUE TITLE
Option to override on demand

### ISSUE THREAD

**Issue by Gfurst** [Samillion/mpv-ytdlautoformat#5]
I was having a hard figuring out why I couldn't get the desired format through `--ytdl-format` until finally finding that I the script installed. I wonder if its possible to add a optional way to override the standard size on demand?

**Comment by Samillion** [comment]
Not possible on demand with this script, as this is just for basic use to set a value for desired quality of specific stream sources.

For on demand and more control for `--ytdl-format`, consider checking out this script instead: [mpv-quality-menu](https://github.com/christoph-heinrich/mpv-quality-menu)
