### ISSUE TITLE
ytdl format did not change when using the ytdl protocol.

### ISSUE THREAD

**Issue by Braeed** [Samillion/mpv-ytdlautoformat#6]
i'm using the extension to call mpv via the ytdl protocol, the output indicates that the ytdl format has been changed. However, when I checked, it was still using the default format.

**Comment by Samillion** [comment]
Could you please show me the log when running the script? Similar to the preview shown in this repo.

**Comment by Braeed** [comment]
here's the screenshot 
![image](https://github.com/Samillion/mpv-ytdlautoformat/assets/106898911/3be64922-0ee4-4bc5-a5a6-93612c9f793a)

**Comment by Samillion** [comment]
Aha! It's not detecting the change due to the `ytdl://` protocol.  You don't need to change `https://` to `ytdl://` in the URL as shown:

![image](https://github.com/Samillion/mpv-ytdlautoformat/assets/17427046/c48c96c4-12de-44c1-9d1d-2b760ac72412)

From [mpv reference](https://mpv.io/manual/master/#protocols):

> ytdl://...
> 
>     By default, the youtube-dl hook script only looks at http(s) URLs. Prefixing an URL with ytdl:// forces it to be always processed by the script. This can also be used to invoke special youtube-dl functionality like playing a video by ID or invoking search.
> 
>     Keep in mind that you can't pass youtube-dl command line options by this, and you have to use --ytdl-raw-options instead.
>

**Comment by Samillion** [comment]
Hmmm. So, if you run mpv with the following:
```
mpv --ytdl-raw-options=format="bv[height<=?480][vcodec!=?vp9]+ba/b[height<=480]" ytdl://www.youtube.com/watch?v=0EtgwIajVqs
```

It'll apply the raw options to the ytdl protocol just fine, I tried to implement it as straight forward as possible, but it ignores it, not sure why.

```lua
local function ytdlAutoChange(name, value)
	local path = string.lower(value)
	local ytdlRaw = 'format="'..ytdlChange..'"'
	
	if StreamSource[getStreamSource(path)] then
		if string.match(path, "^ytdl://") then
			msg.info("Protocol ytdl detected, applying raw options.")
			mp.set_property("ytdl-raw-options", ytdlRaw)
			msg.info("Applied option: "..mp.get_property("ytdl-raw-options"))
		else
			mp.set_property("ytdl-format", ytdlChange)
			msg.info("The ytdl-format has been changed.")
			msg.info("Changed ytdl-format: "..mp.get_property("ytdl-format"))
		end
	else
		msg.info("No domain match, ytdl-format unchanged.")
	end

	mp.unobserve_property(ytdlAutoChange)
	msg.info("Finished check, script no longer running.")
end
```

![image](https://github.com/Samillion/mpv-ytdlautoformat/assets/17427046/b7fc6add-ddee-4ed3-97c0-fa0ecd8fefdf)


I'll have to tinker and play with this one, thought it would be a simple update. 😅 

Until then, use http(s) protocol.

**Comment by Samillion** [comment]
@Braeed Heya. This probably took a long time for me to notice and I'm not sure if you're still having this issue or using the script. Just in case.

This was addressed directly by mpv: https://github.com/mpv-player/mpv/commit/acbd537dac4ce4ea0a9ea316181123000a7082c1

I tried running with `ytdl://` and it worked just fine.

![image](https://github.com/user-attachments/assets/50fcd1c2-7da5-4e74-af6e-7d543c49ef59)

![image](https://github.com/user-attachments/assets/797e5e3d-640c-487d-a966-a4adb0dcbb64)

```
yt-dlp 2024.08.06

mpv v0.38.0-730-g7c672e33 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 31 2024 00:15:54
libplacebo version: v7.349.0 (v7.349.0-9-gefb8934-dirty)
FFmpeg version: N-116820-g8a2c40162
FFmpeg library versions:
   libavcodec      61.11.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.35.100
   libswresample   5.2.100
   libswscale      8.2.100
```
> [!NOTE]
> I've updated the script a bit, though it is mostly a cleanup.

**Comment by Samillion** [comment]
This is driving me insane. I spoke with guido, and he suggested that I should change it to hook with a lower priority than `ytdl_hook.lua`. Still it doesn't work.

Looking at `ytdl_hook.lua`:
https://github.com/mpv-player/mpv/blob/68ea9fecda207210b9c02adf8bcf22dc333cf819/player/lua/ytdl_hook.lua#L1190-L1212

The priorities set are: 10, 20, 50. According to docs, 50 or 0 is the recommended neutral state. So, it would make sense to try and run the script before or after the `ytdl_hook`, to invoke a change or to give the `ytdl_format` property to the `ytdl_hook`. 

Still, doesn't work with lower or higher priority: (5, 6, 10, 20, 50)
```lua
mp.add_hook("on_load", 6, function() ytdlCheck() end)
```

```
      cplayer: Running hook: ytdl_hook/on_load
ytdlautoformat: Domain match found.
       cplayer: Set property: file-local-options/ytdl-format="bv[height<=?720][vcodec!~='vp0?9']+ba/b[height<=720]" -> 1
ytdlautoformat: Changed ytdl-format to: bv[height<=?720][vcodec!~='vp0?9']+ba/b[height<=720]
     ytdl_hook: Starting subprocess: [C:/mpv/yt-dlp.exe, --no-warnings, -J, --flat-playlist, --sub-format, ass/srt/best, --format, bv[vcodec!~='vp0?9']+ba/b, --cookies-from-browser, edge, --all-subs, --no-playlist, --, www.youtube.com/watch?v=IqLyqUdQNcg]
```

What's really bothering me is that I have this feeling that I'm missing something so basic and simple.

I'm re-opening this, I want it to haunt me until I figure it out, and if I don't, I should feel bad about it with this as a reminder.

**Comment by Samillion** [comment]
Finally. Fixed!
